# Generated by Django 2.0 on 2020-06-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=100)),
                ('project_category', models.CharField(max_length=50)),
            ],
        ),
    ]
